# Generated by Django 3.2.5 on 2021-09-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0002_admin__edit_form_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='_edit_form_id',
            new_name='edit_form_id',
        ),
    ]
