# Generated by Django 3.2.5 on 2021-09-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0003_rename__edit_form_id_admin_edit_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='edit_form_id',
        ),
    ]
