# Generated by Django 3.2.5 on 2021-09-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0006_remove_admin_edit_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplytocertifytocourse',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp_app.admin'),
        ),
    ]
