# Generated by Django 3.2.5 on 2021-09-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0007_tutorapplytocertifytocourse_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp_app.tutor'),
        ),
    ]
