# Generated by Django 3.2.5 on 2021-09-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0008_alter_schedule_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='modal_add_link',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='modal_add_student',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='modal_add_tutor',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='modal_remove_student',
        ),
    ]
