# Generated by Django 3.2.5 on 2021-09-16 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0009_auto_20210916_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudents',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp_app.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp_app.tutor'),
        ),
    ]
