# Generated by Django 3.2.5 on 2021-09-17 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0010_auto_20210916_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp_app.admin'),
        ),
    ]
