# Generated by Django 3.2.5 on 2021-09-23 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0012_auto_20210917_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyearnings',
            name='student',
        ),
        migrations.AddField(
            model_name='companyearnings',
            name='student_payment',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='MainApp_app.studentpayment'),
            preserve_default=False,
        ),
    ]
