# Generated by Django 3.2.5 on 2021-09-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0014_remove_companyearnings_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='outstanding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='paid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
