# Generated by Django 3.2.5 on 2021-09-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp_app', '0015_auto_20210923_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnotification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tutornotification',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='AdminNotification',
        ),
        migrations.DeleteModel(
            name='StudentNotification',
        ),
        migrations.DeleteModel(
            name='TutorNotification',
        ),
    ]
